config/routes.rb
Sudoku::Application.routes.draw do
  resources :users


  resources :games


	root :to => 'games#index', :as => 'index'
end

app/models/game.rb
class Game < ActiveRecord::Base
	attr_accessible :completed_at, :initial_state, :state
	serialize :initial_state, Grid
	serialize :state, Grid
	validates_presence_of :user_id

	belongs_to :user

	def self.generate(user)
		g = Grid.generate(10)
		user.games.new(:initial_state => g, :state => g)
	end


	def completed?
		! self.state.data.include?(0)
	end
end

app/models/grid.rb
class Grid

	attr_accessor :data

	def initialize(arr)
		self.data = arr
	end

	def self.dump(grid)
		grid.data.join(',')
	end

	def self.load(str)
		return Grid.new(nil) if str.nil?
		Grid.new(str.split(',').map{ |e| e.to_i })
	end

	def get(x, y)
		self.data[9 * y + x]
	end

	def set(x, y, val)
		self.data[9 * y + x] = val.to_i
	end

	def self.generate(n)
		tab = (0..8).to_a.map{|j| (0..8).to_a.map{|i| (j*3+i+j)%9+1}}.flatten

		(0..n-1).each do |i|
			begin
			n = rand(80)
				end while tab[n] == 0
			tab[n] = 0
		end
		Grid.new(tab)
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :email, :password

	has_many :games
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery

	helper_method :current_user

	private
	def current_user
		@current_user ||= User.first
	end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  # GET /games.json
  def index
    @games = current_user.games

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @games }
    end
  end

  # GET /games/1
  # GET /games/1.json
  def show
    @game = current_user.games.find(params[:id])

	if @game.completed_at.nil?
		redirect_to edit_game_path(@game) and return
	end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/new
  # GET /games/new.json
  def new
    @game = current_user.games.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @game }
    end
  end

  # GET /games/1/edit
  def edit
    @game = current_user.games.find(params[:id])

	if !(@game.completed_at.nil?)
		redirect_to game_path(@game) and return
	end
  end

  # POST /games
  # POST /games.json
  def create
	@game = Game.generate(current_user)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /games/1
  # PUT /games/1.json
  def update
    @game = current_user.games.find(params[:id])

	(0..8).each do |x|
		(0..8).each do |y|
			str = x.to_s + "_" + y.to_s
			if !params[str].blank?
				@game.state.set(x, y, params[str])
			end
		end
	end

	if @game.completed?
		@game.completed_at = Time.now
	end

    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game = current_user.games.find(params[:id])
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :initial_state %><br />
    <%= f.text_field :initial_state %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :completed_at %><br />
    <%= f.date_select :completed_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<p id="notice"><%= notice %></p>

<p>
  <b>State:</b>
<%= form_for(@game) do |f| %>
<table>
  <% (0..8).each do |x| %>
	<tr>
	  <% (0..8).each do |y| %>
		<td>
		  <% val = @game.state.get(x, y) %>
		  <% if @game.initial_state.get(x, y) == 0 %>
			<%= text_field_tag "#{x}_#{y}", val == 0 ? ' ': val %>
		  <% else %>
			<%= @game.state.get(x, y) %></td>
		  <% end %>
	  <% end %>
	</tr>
  <% end %>
</table>
</p>

<p>
  <b>Completed at:</b>
  <%= @game.completed_at %>
</p>
  <div class="actions">
	<%= f.submit %>
  </div>
<% end %>

app/views/games/index.html.erb
<h1>Listing games</h1>

<table>
  <tr>
    <th>Initial state</th>
    <th>State</th>
    <th>Completed at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @games.each do |game| %>
  <tr>
    <td><%= game.initial_state %></td>
    <td><%= game.state %></td>
    <td><%= game.completed_at %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New game</h1>

<%= form_for(@game) do |f| %>
  <div class="actions">
	<%= f.submit %>
  </div>
 <% end %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>State:</b>
  <table>
  <% (0..8).each do |x| %>
	<tr>
	<% (0..8).each do |y| %>
	  <td><%= @game.state.get(x, y) %></td>
		<% end %>
	</tr>
  <% end %>
  </table>
</p>

<p>
  <b>Time:</b>
  <%= @game.completed_at %>
</p>


<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sudoku</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>